export const DEFAULT_MAX_PARTICIPANTS = 30;
export const HEARTBEAT_CRASH_TIMEOUT_MS = 120_000;
export const JOIN_CODE_LENGTH = 6;
export const JOIN_CODE_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
