export declare const DEFAULT_MAX_PARTICIPANTS = 30;
export declare const JOIN_CODE_LENGTH = 6;
export declare const JOIN_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
export declare const CLI_VERSION_HEADER = "x-cli-version";
export declare const USER_ID_HEADER = "x-user-id";
export declare const USER_NAME_HEADER = "x-user-name";
export declare const USER_TOKEN_HEADER = "x-user-token";
export declare const USER_NAME_MAX_LENGTH = 40;
export declare const SECRET_TOKEN_BYTES = 32;
export declare const ORG_NAME_MAX_LENGTH = 12;
export declare const ORG_NAME_PATTERN: RegExp;
