export type ErrorCode =
  | 'RACE_NOT_FOUND'
  | 'RACE_FULL'
  | 'RACE_FINISHED'
  | 'INVALID_TOKEN'
  | 'RATE_LIMITED'
  | 'BAD_REQUEST'
  | 'VERSION_MISMATCH'
  | 'IDENTITY_REQUIRED'
  | 'DUPLICATE_HORSE'
  | 'RACE_OVERLAP'
  | 'ORG_NAME_TAKEN'
  | 'ORG_NOT_FOUND'
  | 'USER_NOT_FOUND'
  | 'NOT_ORG_MEMBER'
  | 'NOT_ORG_OWNER'
  | 'CANNOT_REMOVE_OWNER'
  | 'UNAUTHENTICATED'
  | 'STABLE_HORSE_NOT_FOUND'
  | 'STABLE_HORSE_NAME_TAKEN'
  | 'INSUFFICIENT_ROLLS'
  | 'LEAGUE_CONFLICT'
  | 'CLAIM_NOT_FOUND'
  | 'CLAIM_ALREADY_REDEEMED'
  | 'CLAIM_EXPIRED'
  | 'JOIN_TOKEN_DISABLED'
  | 'DOMAIN_NOT_ALLOWED'
  | 'EMAIL_REQUIRED'
  | 'DOMAIN_ALREADY_CLAIMED'
  | 'ALLOW_LIST_REQUIRED'
  | 'CLI_AUTH_NOT_FOUND'
  | 'CLI_AUTH_WRONG_ACCOUNT'
  | 'DEVICE_NOT_FOUND';

export type ErrorEnvelope = {
  code: ErrorCode;
  message: string;
};

export const ERROR_STATUS: Record<ErrorCode, number> = {
  BAD_REQUEST: 400,
  IDENTITY_REQUIRED: 400,
  EMAIL_REQUIRED: 400,
  ALLOW_LIST_REQUIRED: 400,
  INVALID_TOKEN: 401,
  UNAUTHENTICATED: 401,
  INSUFFICIENT_ROLLS: 402,
  NOT_ORG_MEMBER: 403,
  NOT_ORG_OWNER: 403,
  CANNOT_REMOVE_OWNER: 409,
  CLI_AUTH_WRONG_ACCOUNT: 403,
  JOIN_TOKEN_DISABLED: 403,
  DOMAIN_NOT_ALLOWED: 403,
  RACE_NOT_FOUND: 404,
  ORG_NOT_FOUND: 404,
  USER_NOT_FOUND: 404,
  STABLE_HORSE_NOT_FOUND: 404,
  CLAIM_NOT_FOUND: 404,
  CLI_AUTH_NOT_FOUND: 404,
  DEVICE_NOT_FOUND: 404,
  RACE_FULL: 409,
  RACE_OVERLAP: 409,
  DUPLICATE_HORSE: 409,
  ORG_NAME_TAKEN: 409,
  STABLE_HORSE_NAME_TAKEN: 409,
  LEAGUE_CONFLICT: 409,
  CLAIM_ALREADY_REDEEMED: 409,
  DOMAIN_ALREADY_CLAIMED: 409,
  RACE_FINISHED: 410,
  CLAIM_EXPIRED: 410,
  VERSION_MISMATCH: 426,
  RATE_LIMITED: 429,
};
