export type ErrorCode =
  | 'RACE_NOT_FOUND'
  | 'RACE_FULL'
  | 'RACE_FINISHED'
  | 'INVALID_TOKEN'
  | 'RATE_LIMITED'
  | 'BAD_REQUEST'
  | 'VERSION_MISMATCH'
  | 'IDENTITY_REQUIRED'
  | 'DUPLICATE_HORSE'
  | 'ORG_NAME_TAKEN'
  | 'ORG_NOT_FOUND'
  | 'NOT_ORG_MEMBER'
  | 'NOT_ORG_OWNER'
  | 'UNAUTHENTICATED'
  | 'STABLE_HORSE_NOT_FOUND'
  | 'STABLE_HORSE_NAME_TAKEN';

export type ErrorEnvelope = {
  code: ErrorCode;
  message: string;
};

export const ERROR_STATUS: Record<ErrorCode, number> = {
  BAD_REQUEST: 400,
  IDENTITY_REQUIRED: 400,
  INVALID_TOKEN: 401,
  UNAUTHENTICATED: 401,
  NOT_ORG_MEMBER: 403,
  NOT_ORG_OWNER: 403,
  RACE_NOT_FOUND: 404,
  ORG_NOT_FOUND: 404,
  STABLE_HORSE_NOT_FOUND: 404,
  RACE_FULL: 409,
  DUPLICATE_HORSE: 409,
  ORG_NAME_TAKEN: 409,
  STABLE_HORSE_NAME_TAKEN: 409,
  RACE_FINISHED: 410,
  VERSION_MISMATCH: 426,
  RATE_LIMITED: 429,
};
