// Cosmetic hat catalog. Each hat ships with one or more colour variants
// (legendary hats are exceptions — single design, animated). The roll
// handler picks rarity tier → hat → variant uniformly. Catalog is edited
// via `tools/hat-editor/index.html` and exported to this file by
// pasting the result over the HATS array.

import type { Hat, HatId } from './types.js';

export function hatById(id: HatId): Hat | undefined {
  return HATS.find(h => h.id === id);
}

export const HATS: Hat[] = [
  // ── COMMON (18) ────────────────────────────────────────────────────────
  { id: 'flat_cap', name: "Flat Cap", rarity: 'common', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...........','...........','...........','....AAAA...','...AAAAAA..','..AAAAAAA..'], variants: [{ A: '#8B6914' }, { A: '#12301b' }, { A: '#aab5cb' }, { A: '#bdcbaa' }] , rollable: true },
  { id: 'bucket_hat', name: "Bucket Hat", rarity: 'common', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...........','...........','...QQQQQ...','...AAAAA...','...AAAAA...','.AAAAAAAAA.'], variants: [{ A: '#CC2200', Q: '#FFFFFF' }, { A: '#0007cc', Q: '#FFFFFF' }, { A: '#becc00', Q: '#4d3dc7' }, { A: '#cc00c5', Q: '#d6d6dc' }] , rollable: true },
  { id: 'beanie', name: "Beanie", rarity: 'common', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...........','...........','....AAA....','...AAAAA...','...AAAAA...','..AAAAAAA..'], variants: [{ A: '#4A7C59' }, { A: '#b21f35' }, { A: '#ec9418' }, { A: '#3a17e6' }] , rollable: true },
  { id: 'stetson', name: "Stetson", rarity: 'common', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...AA.AA...','...AAAAA...','...AAAAA...','A..AAAAA..A','AAAAAAAAAAA','AAAAAAAAAAA'], variants: [{ A: '#C49A00' }, { A: '#272004' }, { A: '#040404' }, { A: '#373606' }] , rollable: true },
  { id: 'party_hat', name: "Party Hat", rarity: 'common', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...........','.....A.....','....AAA....','....AQA....','...AQAQA...','...AAAAA...'], variants: [{ A: '#FF69B4', Q: '#FFD700' }, { A: '#c46bff', Q: '#ff000d' }, { A: '#fdff6b', Q: '#0400ff' }, { A: '#6bff97', Q: '#05050a' }] , rollable: true },
  { id: 'fez', name: "Fez", rarity: 'common', width: 11, anchor_x: 22, rows: ['...........','...........','...........','...........','...........','...........','....Q......','....AAA....','....AAA....','....AAA....'], variants: [{ A: '#CC0000', Q: '#8B0000' }, { A: '#CC0000', Q: '#f5e5e5' }, { A: '#CC0000', Q: '#f1e209' }, { A: '#CC0000', Q: '#0956f1' }] , rollable: true },
  { id: 'sailor_hat', name: "Sailor Hat", rarity: 'common', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...........','...........','...QQQQQ...','..AAAAAAA..','..QQQQQQQ..','..AAAAAAA..'], variants: [{ A: '#FFFFFF', Q: '#000080' }, { A: '#FFFFFF', Q: '#c0c0ed' }, { A: '#FFFFFF', Q: '#00000a' }, { A: '#FFFFFF', Q: '#0505ef' }] , rollable: true },
  { id: 'newsboy_cap', name: "Newsboy Cap", rarity: 'common', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...........','...........','...AAAAA...','..AAAQAAA..','..AAAAAAA..','..AAAAAA...'], variants: [{ A: '#5C4033', Q: '#3D2B1F' }, { A: '#e96020', Q: '#131211' }, { A: '#342c28', Q: '#131211' }, { A: '#0a0300', Q: '#ddab78' }] , rollable: true },
  { id: 'tam_o_shanter', name: "Tam O'Shanter", rarity: 'common', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...........','.....Q.....','....AAA....','..AAAAAAA..','..AAAAAAA..','...AAAAA...'], variants: [{ A: '#006400', Q: '#FF0000' }, { A: '#ff0000', Q: '#016400' }] , rollable: true },
  { id: 'trucker_cap', name: "Trucker Cap", rarity: 'common', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...........','...........','...AAQQ....','...AAQQ....','..AAQQQAA..','..AAQQQAA..'], variants: [{ A: '#2196F3', Q: '#FFFFFF' }, { A: '#f41fe3', Q: '#FFFFFF' }, { A: '#1ff45f', Q: '#FFFFFF' }] , rollable: true },
  { id: 'hard_hat', name: "Hard Hat", rarity: 'common', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...........','...........','....AAA....','...AAAAA...','..AAAAAAA..','..AAAAAAAAA'], variants: [{ A: '#FFD600' }, { A: '#d74c1d' }] , rollable: true },
  { id: 'chef_toque', name: "Chef's Toque", rarity: 'common', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...AAAAA...','..AAQAQAA..','...AQAQA...','...AQAQA...','...AQAQA...','...AAAAA...'], variants: [{ A: '#FFFFFF', Q: '#f9f9f9' }] , rollable: true },
  { id: 'bobble_hat', name: "Bobble Hat", rarity: 'common', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...........','...........','.....Q.....','...AAAAA...','...AAAAA...','..AAAAAAA..'], variants: [{ A: '#C62828', Q: '#FFFFFF' }, { A: '#293bc7', Q: '#FFFFFF' }, { A: '#29c775', Q: '#231f1f' }, { A: '#a529c7', Q: '#d50707' }] , rollable: true },
  { id: 'cowboy_hat', name: "Cowboy Hat", rarity: 'common', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...........','...........','...AAAAA...','...AAAAA...','A.AAAAAAA.A','.AAAAAAAAA.'], variants: [{ A: '#8B4513' }, { A: '#0a0400' }, { A: '#956c50' }] , rollable: true },
  { id: 'baseball_cap', name: "Baseball Cap", rarity: 'common', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...........','...........','...AAAAA...','..AAAAAA...','..AAAAAAA..','..AAAAAAAAA'], variants: [{ A: '#1565C0' }, { A: '#8515c1' }, { A: '#15c157' }, { A: '#ef2d0b' }] , rollable: true },
  { id: 'tinfoil_hat', name: "Tinfoil Hat", rarity: 'common', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...........','...........','.....A.....','....AAA....','...AAAAA...','..AAAAAAA..'], variants: [{ A: '#B0BEC5' }, { A: '#6a6c6c' }] , rollable: true },
  { id: 'dunce_cap', name: "Dunce Cap", rarity: 'common', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','.....Q.....','....QAQ....','...QAAAQ...','...QAAAQ...','..QAAAAAQ..','..AAAAAAA..'], variants: [{ A: '#F8F8F8', Q: '#F44336' }] , rollable: true },
  { id: 'mini_top_hat', name: "Mini Top Hat", rarity: 'common', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...........','...AAAAA...','...AAAAA...','...AAAAA...','..AAAAAAA..','..AAAAAAA..'], variants: [{ A: '#212121' }, { A: '#626060' }] , rollable: true },
  // ── RARE (10) ──────────────────────────────────────────────────────────
  { id: 'bicorne', name: "Bicorne", rarity: 'rare', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...........','...........','..AAAQQQQ..','..AAAAAAA..','..AAAAAAA..','...QQQQQ...'], variants: [{ A: '#1A237E', Q: '#FFD700' }, { A: '#01052d', Q: '#544803' }] , rollable: true },
  { id: 'viking_helmet', name: "Viking Helmet", rarity: 'rare', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...........','...........','..A.AAA.A..','..AAAAAAA..','..AAAAAAA..','..AQQQQQA..'], variants: [{ A: '#9E9E9E', Q: '#8D6E63' }, { A: '#dcdbdb', Q: '#bf3908' }] , rollable: true },
  { id: 'jesters_cap', name: "Jester's Cap", rarity: 'rare', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...........','...........','..AQAQAQA..','..AQAQAQA..','...AAAAA...','...AAAAA...'], variants: [{ A: '#E53935', Q: '#FFD600' }, { A: '#e5a434', Q: '#0040ff' }, { A: '#34e537', Q: '#eeff00' }, { A: '#e234e5', Q: '#00ff40' }] , rollable: true },
  { id: 'plague_doctor', name: "Plague Doctor Beak", rarity: 'rare', width: 11, anchor_x: 24, rows: ['...........','...........','...........','...........','....QQQ....','...QAAAQQ..','...QQQQQQQ.','..QQQQQ.QQQ','..QQQQ....Q','..QQQQ.....'], variants: [{ A: '#F5F5F5', Q: '#795548' }, { A: '#e1dbdb', Q: '#080707' }] , rollable: true },
  { id: 'morion', name: "Conquistador Morion", rarity: 'rare', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...........','.....Q.....','...QQQQQ...','...QAAAQ...','.A..AAA..A.','..AAQQQAA..'], variants: [{ A: '#B0BEC5', Q: '#FFD600' }, { A: '#0a4768', Q: '#e6c10a' }] , rollable: true },
  { id: 'shako', name: "Shako", rarity: 'rare', width: 11, anchor_x: 23, rows: ['...........','...........','........Q..','........Q..','........Q..','........Q..','..AAAAAAA..','..AAAAAAA..','..AAAAAAA..','..AQQQQQA..'], variants: [{ A: '#45464f', Q: '#00ff2a' }, { A: '#45464f', Q: '#ff4d00' }, { A: '#45464f', Q: '#ff0019' }, { A: '#45464f', Q: '#fff700' }] , rollable: true },
  { id: 'centurion_helm', name: "Centurion Helm", rarity: 'rare', width: 11, anchor_x: 23, rows: ['...........','...........','....QQQ....','...QQQQQQ..','..QQQQQQQQ.','.QQ..A...Q.','.Q..AAA....','...AAAAA...','..AAAAAAA..','..AAAAAAA..'], variants: [{ A: '#B0BEC5', Q: '#C62828' }, { A: '#2f3131', Q: '#C62828' }] , rollable: true },
  { id: 'papal_mitre', name: "Papal Mitre", rarity: 'rare', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...........','...........','....QQQ....','...QQQQQ...','...QAAAQ...','..AAAAAAA..'], variants: [{ A: '#FFFFFF', Q: '#FFD700' }] , rollable: true },
  { id: 'headdress', name: "Headdress", rarity: 'rare', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...........','...........','..AQAQAQA..','..AQAQAQA..','..AAAAAAA..','...QQQQQ...'], variants: [{ A: '#FF8F00', Q: '#1565C0' }] , rollable: true },
  { id: 'sombrero', name: "Sombrero", rarity: 'rare', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...........','.....A.....','....AAA....','...AAAAA...','...AQAQA...','AAAAAAAAAAA'], variants: [{ A: '#F57F17', Q: '#BF360C' }, { A: '#f8b377', Q: '#3e1204' }, { A: '#d6f877', Q: '#04133e' }, { A: '#d6f877', Q: '#04133e' }] , rollable: true },
  // ── EPIC (6) ───────────────────────────────────────────────────────────
  { id: 'papal_tiara', name: "Papal Tiara", rarity: 'epic', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','....QQ.....','...QQQQQ...','...QAAQQ...','...QQQQQ...','..AAAAAAA..','..AQQQQQA..'], variants: [{ A: '#FFFFFF', Q: '#FFD700' }, { A: '#b18e10', Q: '#f3f3f1' }] , rollable: true },
  { id: 'samurai_kabuto', name: "Samurai Kabuto", rarity: 'epic', width: 11, anchor_x: 23, rows: ['....Q...Q..','....QQ.QQ..','.....QQQ...','.......Q...','...AAAAQ...','..AAAAAQQ..','..AAAAAQQ..','.AAAAAAAQ..','AAAAAAAAQ..','AAAAAAAAQ..'], variants: [{ A: '#B0BEC5', Q: '#C62828' }, { A: '#050505', Q: '#C62828' }, { A: '#675f5f', Q: '#c4c729' }] , rollable: true },
  { id: 'gladiator_galea', name: "Gladiator Galea", rarity: 'epic', width: 11, anchor_x: 23, rows: ['...........','...........','...........','....QQQQQQ.','...QQQQQ...','...QQQQQ...','...QAAA....','..AAAAAAA..','..AAAAAAA..','..AQQQQQA..'], variants: [{ A: '#B0BEC5', Q: '#C62828' }, { A: '#ffe907', Q: '#C62828' }] , rollable: true },
  { id: 'pharaoh_nemes', name: "Pharaoh Nemes", rarity: 'epic', width: 11, anchor_x: 23, rows: ['...........','...........','...........','..AAAAAAA..','..AAQAQAA..','..QAQAQAQ..','..QAQAQAQ..','..QQAAAQQ..','..QQAAAAA..','...QAQA....'], variants: [{ A: '#FFD700', Q: '#1565C0' }, { A: '#8d342a', Q: '#63686e' }] , rollable: true },
  { id: 'spartan_helmet', name: "Spartan Helmet", rarity: 'epic', width: 11, anchor_x: 23, rows: ['...........','........Q..','.......QQ..','.....QQQQ..','....QQQQQ..','..QQQQQQ...','.QQQAA.....','QQAAAAAAA..','Q.AAAAAAA..','..AQQQQQA..'], variants: [{ A: '#B0BEC5', Q: '#B71C1C' }, { A: '#B0BEC5', Q: '#b2b51c' }, { A: '#B0BEC5', Q: '#b5611c' }] , rollable: true },
  { id: 'conquistador_full', name: "Conquistador Helm", rarity: 'epic', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','.....A.....','....AAA....','...AAAAA...','..AAAAAAA..','...AQQQA...','...AQQQA...'], variants: [{ A: '#B0BEC5', Q: '#FFD700' }, { A: '#B0BEC5', Q: '#0040ff' }, { A: '#B0BEC5', Q: '#36123b' }] , rollable: true },
  // ── LEGENDARY (5) ──────────────────────────────────────────────────────
  { id: 'rainbow_crown', name: "Rainbow Crown", rarity: 'legendary', width: 11, anchor_x: 23, rows: ['...........','...........','.....A.....','....AAA....','....AQA....','....AAA....','...AAQAA...','...AAAAA...','..AAAQAAA..','..AAAAAAA..'], colors: { A: '#FFD700', Q: '#553f3f' }, animation: { type: 'cycle', frames: ['#FF0000','#FF7F00','#FFFF00','#00FF00','#0000FF','#8B00FF'], fps: 8 } , rollable: true },
  { id: 'inferno_cap', name: "Inferno Cap", rarity: 'legendary', width: 11, anchor_x: 23, rows: ['...........','....AAA....','...AAAAA...','....AAA....','.....Q.....','A....Q....A','A...QQQ...A','.A..QQQ..A.','..AAAAAAA..','..AAAAAAA..'], colors: { A: '#FF4500', Q: '#FFD700' }, animation: { type: 'cycle', frames: ['#FF0000','#FF2200','#FF4500','#FF6600','#FF8C00','#FFA500'], fps: 12 } , rollable: true },
  { id: 'void_hood', name: "Void Hood", rarity: 'legendary', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...AAA.....','..AAAAAA...','.AAAAAAA...','.AAAAAAAA..','AAAAAAAAA..','AAAAQQQAA..','AAAAQQQAA..'], colors: { A: '#1A0033', Q: '#d9cfe3' }, animation: { type: 'cycle', frames: ['#0D0019','#1A0033','#2D004D','#3D0066','#2D004D','#1A0033'], fps: 3 } , rollable: true },
  { id: 'prismatic_jester', name: "Prismatic Jester", rarity: 'legendary', width: 11, anchor_x: 23, rows: ['...........','..Q.Q.Q.Q..','Q..A.A.A..Q','.Q.A.A.A.Q.','..AQAQAQA..','..AQAQAQA..','..AAAAAAA..','..AAAAAAA..','..AAAAAAA..','..AAAAAAA..'], colors: { A: '#FF0000', Q: '#0000FF' }, animation: { type: 'cycle', frames: ['#FF0000','#FF7F00','#FFFF00','#00FF00','#0000FF','#8B00FF','#FF00FF','#00FFFF'], fps: 15 } , rollable: true },
  { id: 'aurora_helm', name: "Aurora Helm", rarity: 'legendary', width: 11, anchor_x: 23, rows: ['...........','...........','...........','...........','...QQQQQ...','...QQQQQ...','..AAAAAAA..','..AAAAAAA..','..AQAAAQA..','..AQAAAQA..'], colors: { A: '#00CED1', Q: '#00FF7F' }, animation: { type: 'cycle', frames: ['#0000FF','#0066FF','#00BFFF','#00CED1','#00FF7F','#7CFC00','#00FF7F','#00CED1'], fps: 4 } , rollable: true },
  // Claim-only: awarded by an admin, never from a roll. Only the A channel cycles,
  // so the inset motif shifts colour while the cap body stays a static rust brown.
  // The body colour is kept out of the frame list so the motif never merges into it.
  { id: 'contributor_cap', name: "Contributor Cap", rarity: 'legendary', width: 11, anchor_x: 23, rows: ['.....Q.....','....QQQ....','...QQQQQ...','..QAAAQQQ..','..QQAQQQQ..','.QQQAQAAQQ.','.QQQAQAQAQ.','.QQQQQAQAQ.','.QQQQQAAQQ.','.QQQQQQQQQ.'], colors: { A: '#21138b', Q: '#6f2801' }, animation: { type: 'cycle', frames: ['#FF8C42','#E0457B','#8B5CF6','#3B82F6','#22D3EE','#34D399','#A3E635','#FBBF24'], fps: 6 }, rollable: false },
];
